# Permalinks
permalink:           /:title/

# Setup
title:               nashp.com
tagline:             I'm Nash. I Create Things.
url:                 https://nashp.com
paginate:            1
baseurl:             "https://nashpitre.github.io"

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nash Pitre
  url:               https://twitter.com/nashp
  email:             nashp@me.com

# Other
timezone:            America/Chicago

# Custom vars
version:             4.0.0
github:              https://github.com/nashpitre/
repo:                https://github.com/nashpitre/nashpitre.github.io